### PR TITLE
without this we got BT error

### PR DESCRIPTION
**Pull request by bartcubbins**

### CODE REVIEW

**Comment by alviteri** [comment]
this should be configured somewhere else not here

**Comment by alviteri** [comment]
here https://github.com/bartcubbins/platform_hardware_qcom_bt/blob/android-7.1/msm8992/Android.mk#L1

**Comment by bartcubbins** [comment]
oh, I forget about Android.mk changes in common

**Comment by alviteri** [comment]
https://github.com/SonyAosp/device_sony_common/commit/077406946e9e634d6e730050843476460eca5554

**Pull request closed without merging**
